/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as landingpageIndexRouteImport } from './routes/(landingpage)/index'

const landingpageIndexRoute = landingpageIndexRouteImport.update({
  id: '/(landingpage)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof landingpageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof landingpageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(landingpage)/': typeof landingpageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(landingpage)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  landingpageIndexRoute: typeof landingpageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(landingpage)/': {
      id: '/(landingpage)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingpageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  landingpageIndexRoute: landingpageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
