/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as adminAdminDashboardRouteImport } from './routes/(admin)/admin-dashboard'
import { Route as assistingLawyersAssistingDashboardRouteImport } from './routes/(assisting-lawyers)/assisting-dashboard'
import { Route as engagingLaywersEngagingDashboardRouteImport } from './routes/(engaging-laywers)/engaging-dashboard'
import { Route as landingpageIndexRouteImport } from './routes/(landingpage)/index'
import { Route as adminAdminDashboardIndexRouteImport } from './routes/(admin)/admin-dashboard/index'
import { Route as adminAdminDashboardAnnouncementsRouteImport } from './routes/(admin)/admin-dashboard/announcements'
import { Route as adminAdminDashboardFinanceRouteImport } from './routes/(admin)/admin-dashboard/finance'
import { Route as adminAdminDashboardLawyersRouteImport } from './routes/(admin)/admin-dashboard/lawyers'
import { Route as adminAdminDashboardReportRouteImport } from './routes/(admin)/admin-dashboard/report'
import { Route as adminAdminDashboardRolesRouteImport } from './routes/(admin)/admin-dashboard/roles'
import { Route as adminAdminDashboardTasksRouteImport } from './routes/(admin)/admin-dashboard/tasks'
import { Route as assistingLawyersAssistingDashboardIndexRouteImport } from './routes/(assisting-lawyers)/assisting-dashboard/index'
import { Route as assistingLawyersAssistingDashboardMessagesRouteImport } from './routes/(assisting-lawyers)/assisting-dashboard/messages'
import { Route as assistingLawyersAssistingDashboardNotificationsRouteImport } from './routes/(assisting-lawyers)/assisting-dashboard/notifications'
import { Route as assistingLawyersAssistingDashboardPaymentsRouteImport } from './routes/(assisting-lawyers)/assisting-dashboard/payments'
import { Route as assistingLawyersAssistingDashboardProfileRouteImport } from './routes/(assisting-lawyers)/assisting-dashboard/profile'
import { Route as assistingLawyersAssistingDashboardProposalsRouteImport } from './routes/(assisting-lawyers)/assisting-dashboard/proposals'
import { Route as engagingLaywersEngagingDashboardIndexRouteImport } from './routes/(engaging-laywers)/engaging-dashboard/index'
import { Route as engagingLaywersEngagingDashboardMessagesRouteImport } from './routes/(engaging-laywers)/engaging-dashboard/messages'
import { Route as engagingLaywersEngagingDashboardNotificationsRouteImport } from './routes/(engaging-laywers)/engaging-dashboard/notifications'
import { Route as engagingLaywersEngagingDashboardPaymentsRouteImport } from './routes/(engaging-laywers)/engaging-dashboard/payments'
import { Route as engagingLaywersEngagingDashboardPostJobRouteImport } from './routes/(engaging-laywers)/engaging-dashboard/post-job'
import { Route as engagingLaywersEngagingDashboardRatingsRouteImport } from './routes/(engaging-laywers)/engaging-dashboard/ratings'
import { Route as engagingLaywersEngagingDashboardSettingsRouteImport } from './routes/(engaging-laywers)/engaging-dashboard/settings'
import { Route as adminAdminDashboardLawyersIndexRouteImport } from './routes/(admin)/admin-dashboard/lawyers/index'
import { Route as adminAdminDashboardLawyersLawyerIdRouteImport } from './routes/(admin)/admin-dashboard/lawyers.$lawyerId'
import { Route as adminAdminDashboardTasksIndexRouteImport } from './routes/(admin)/admin-dashboard/tasks/index'
import { Route as adminAdminDashboardTasksTaskIdRouteImport } from './routes/(admin)/admin-dashboard/tasks.$taskId'
import { Route as assistingLawyersAssistingDashboardApplyTaskIdRouteImport } from './routes/(assisting-lawyers)/assisting-dashboard/apply.$taskId'
import { Route as assistingLawyersAssistingDashboardMessagesTaskIdRouteImport } from './routes/(assisting-lawyers)/assisting-dashboard/messages.$taskId'
import { Route as assistingLawyersAssistingDashboardRequestSentTaskIdRouteImport } from './routes/(assisting-lawyers)/assisting-dashboard/request-sent.$taskId'
import { Route as assistingLawyersAssistingDashboardTaskTaskIdRouteImport } from './routes/(assisting-lawyers)/assisting-dashboard/task.$taskId'
import { Route as engagingLaywersAuthLoginIndexRouteImport } from './routes/(engaging-laywers)/auth/login/index'
import { Route as engagingLaywersAuthRegisterIndexRouteImport } from './routes/(engaging-laywers)/auth/register/index'
import { Route as engagingLaywersEngagingDashboardFundTaskTaskIdRouteImport } from './routes/(engaging-laywers)/engaging-dashboard/fund-task.$taskId'
import { Route as engagingLaywersEngagingDashboardMessagesTaskIdRouteImport } from './routes/(engaging-laywers)/engaging-dashboard/messages.$taskId'
import { Route as engagingLaywersEngagingDashboardReviewProposalsTaskIdRouteImport } from './routes/(engaging-laywers)/engaging-dashboard/review-proposals.$taskId'
import { Route as engagingLaywersEngagingDashboardReviewWorkTaskIdRouteImport } from './routes/(engaging-laywers)/engaging-dashboard/review-work.$taskId'
import { Route as engagingLaywersEngagingDashboardSubmitRatingTaskIdRouteImport } from './routes/(engaging-laywers)/engaging-dashboard/submit-rating.$taskId'
import { Route as engagingLaywersEngagingDashboardYourRatingTaskIdRouteImport } from './routes/(engaging-laywers)/engaging-dashboard/your-rating.$taskId'

const adminAdminDashboardRoute = adminAdminDashboardRouteImport.update({
  id: '/(admin)/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const assistingLawyersAssistingDashboardRoute =
  assistingLawyersAssistingDashboardRouteImport.update({
    id: '/(assisting-lawyers)/assisting-dashboard',
    path: '/assisting-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const engagingLaywersEngagingDashboardRoute =
  engagingLaywersEngagingDashboardRouteImport.update({
    id: '/(engaging-laywers)/engaging-dashboard',
    path: '/engaging-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const landingpageIndexRoute = landingpageIndexRouteImport.update({
  id: '/(landingpage)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAdminDashboardIndexRoute =
  adminAdminDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminAdminDashboardRoute,
  } as any)
const adminAdminDashboardAnnouncementsRoute =
  adminAdminDashboardAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => adminAdminDashboardRoute,
  } as any)
const adminAdminDashboardFinanceRoute =
  adminAdminDashboardFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => adminAdminDashboardRoute,
  } as any)
const adminAdminDashboardLawyersRoute =
  adminAdminDashboardLawyersRouteImport.update({
    id: '/lawyers',
    path: '/lawyers',
    getParentRoute: () => adminAdminDashboardRoute,
  } as any)
const adminAdminDashboardReportRoute =
  adminAdminDashboardReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => adminAdminDashboardRoute,
  } as any)
const adminAdminDashboardRolesRoute =
  adminAdminDashboardRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => adminAdminDashboardRoute,
  } as any)
const adminAdminDashboardTasksRoute =
  adminAdminDashboardTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => adminAdminDashboardRoute,
  } as any)
const assistingLawyersAssistingDashboardIndexRoute =
  assistingLawyersAssistingDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => assistingLawyersAssistingDashboardRoute,
  } as any)
const assistingLawyersAssistingDashboardMessagesRoute =
  assistingLawyersAssistingDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => assistingLawyersAssistingDashboardRoute,
  } as any)
const assistingLawyersAssistingDashboardNotificationsRoute =
  assistingLawyersAssistingDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => assistingLawyersAssistingDashboardRoute,
  } as any)
const assistingLawyersAssistingDashboardPaymentsRoute =
  assistingLawyersAssistingDashboardPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => assistingLawyersAssistingDashboardRoute,
  } as any)
const assistingLawyersAssistingDashboardProfileRoute =
  assistingLawyersAssistingDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => assistingLawyersAssistingDashboardRoute,
  } as any)
const assistingLawyersAssistingDashboardProposalsRoute =
  assistingLawyersAssistingDashboardProposalsRouteImport.update({
    id: '/proposals',
    path: '/proposals',
    getParentRoute: () => assistingLawyersAssistingDashboardRoute,
  } as any)
const engagingLaywersEngagingDashboardIndexRoute =
  engagingLaywersEngagingDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => engagingLaywersEngagingDashboardRoute,
  } as any)
const engagingLaywersEngagingDashboardMessagesRoute =
  engagingLaywersEngagingDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => engagingLaywersEngagingDashboardRoute,
  } as any)
const engagingLaywersEngagingDashboardNotificationsRoute =
  engagingLaywersEngagingDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => engagingLaywersEngagingDashboardRoute,
  } as any)
const engagingLaywersEngagingDashboardPaymentsRoute =
  engagingLaywersEngagingDashboardPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => engagingLaywersEngagingDashboardRoute,
  } as any)
const engagingLaywersEngagingDashboardPostJobRoute =
  engagingLaywersEngagingDashboardPostJobRouteImport.update({
    id: '/post-job',
    path: '/post-job',
    getParentRoute: () => engagingLaywersEngagingDashboardRoute,
  } as any)
const engagingLaywersEngagingDashboardRatingsRoute =
  engagingLaywersEngagingDashboardRatingsRouteImport.update({
    id: '/ratings',
    path: '/ratings',
    getParentRoute: () => engagingLaywersEngagingDashboardRoute,
  } as any)
const engagingLaywersEngagingDashboardSettingsRoute =
  engagingLaywersEngagingDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => engagingLaywersEngagingDashboardRoute,
  } as any)
const adminAdminDashboardLawyersIndexRoute =
  adminAdminDashboardLawyersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminAdminDashboardLawyersRoute,
  } as any)
const adminAdminDashboardLawyersLawyerIdRoute =
  adminAdminDashboardLawyersLawyerIdRouteImport.update({
    id: '/$lawyerId',
    path: '/$lawyerId',
    getParentRoute: () => adminAdminDashboardLawyersRoute,
  } as any)
const adminAdminDashboardTasksIndexRoute =
  adminAdminDashboardTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminAdminDashboardTasksRoute,
  } as any)
const adminAdminDashboardTasksTaskIdRoute =
  adminAdminDashboardTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => adminAdminDashboardTasksRoute,
  } as any)
const assistingLawyersAssistingDashboardApplyTaskIdRoute =
  assistingLawyersAssistingDashboardApplyTaskIdRouteImport.update({
    id: '/apply/$taskId',
    path: '/apply/$taskId',
    getParentRoute: () => assistingLawyersAssistingDashboardRoute,
  } as any)
const assistingLawyersAssistingDashboardMessagesTaskIdRoute =
  assistingLawyersAssistingDashboardMessagesTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => assistingLawyersAssistingDashboardMessagesRoute,
  } as any)
const assistingLawyersAssistingDashboardRequestSentTaskIdRoute =
  assistingLawyersAssistingDashboardRequestSentTaskIdRouteImport.update({
    id: '/request-sent/$taskId',
    path: '/request-sent/$taskId',
    getParentRoute: () => assistingLawyersAssistingDashboardRoute,
  } as any)
const assistingLawyersAssistingDashboardTaskTaskIdRoute =
  assistingLawyersAssistingDashboardTaskTaskIdRouteImport.update({
    id: '/task/$taskId',
    path: '/task/$taskId',
    getParentRoute: () => assistingLawyersAssistingDashboardRoute,
  } as any)
const engagingLaywersAuthLoginIndexRoute =
  engagingLaywersAuthLoginIndexRouteImport.update({
    id: '/(engaging-laywers)/auth/login/',
    path: '/auth/login/',
    getParentRoute: () => rootRouteImport,
  } as any)
const engagingLaywersAuthRegisterIndexRoute =
  engagingLaywersAuthRegisterIndexRouteImport.update({
    id: '/(engaging-laywers)/auth/register/',
    path: '/auth/register/',
    getParentRoute: () => rootRouteImport,
  } as any)
const engagingLaywersEngagingDashboardFundTaskTaskIdRoute =
  engagingLaywersEngagingDashboardFundTaskTaskIdRouteImport.update({
    id: '/fund-task/$taskId',
    path: '/fund-task/$taskId',
    getParentRoute: () => engagingLaywersEngagingDashboardRoute,
  } as any)
const engagingLaywersEngagingDashboardMessagesTaskIdRoute =
  engagingLaywersEngagingDashboardMessagesTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => engagingLaywersEngagingDashboardMessagesRoute,
  } as any)
const engagingLaywersEngagingDashboardReviewProposalsTaskIdRoute =
  engagingLaywersEngagingDashboardReviewProposalsTaskIdRouteImport.update({
    id: '/review-proposals/$taskId',
    path: '/review-proposals/$taskId',
    getParentRoute: () => engagingLaywersEngagingDashboardRoute,
  } as any)
const engagingLaywersEngagingDashboardReviewWorkTaskIdRoute =
  engagingLaywersEngagingDashboardReviewWorkTaskIdRouteImport.update({
    id: '/review-work/$taskId',
    path: '/review-work/$taskId',
    getParentRoute: () => engagingLaywersEngagingDashboardRoute,
  } as any)
const engagingLaywersEngagingDashboardSubmitRatingTaskIdRoute =
  engagingLaywersEngagingDashboardSubmitRatingTaskIdRouteImport.update({
    id: '/submit-rating/$taskId',
    path: '/submit-rating/$taskId',
    getParentRoute: () => engagingLaywersEngagingDashboardRoute,
  } as any)
const engagingLaywersEngagingDashboardYourRatingTaskIdRoute =
  engagingLaywersEngagingDashboardYourRatingTaskIdRouteImport.update({
    id: '/your-rating/$taskId',
    path: '/your-rating/$taskId',
    getParentRoute: () => engagingLaywersEngagingDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin-dashboard': typeof adminAdminDashboardRouteWithChildren
  '/assisting-dashboard': typeof assistingLawyersAssistingDashboardRouteWithChildren
  '/engaging-dashboard': typeof engagingLaywersEngagingDashboardRouteWithChildren
  '/': typeof landingpageIndexRoute
  '/admin-dashboard/announcements': typeof adminAdminDashboardAnnouncementsRoute
  '/admin-dashboard/finance': typeof adminAdminDashboardFinanceRoute
  '/admin-dashboard/lawyers': typeof adminAdminDashboardLawyersRouteWithChildren
  '/admin-dashboard/report': typeof adminAdminDashboardReportRoute
  '/admin-dashboard/roles': typeof adminAdminDashboardRolesRoute
  '/admin-dashboard/tasks': typeof adminAdminDashboardTasksRouteWithChildren
  '/assisting-dashboard/messages': typeof assistingLawyersAssistingDashboardMessagesRouteWithChildren
  '/assisting-dashboard/notifications': typeof assistingLawyersAssistingDashboardNotificationsRoute
  '/assisting-dashboard/payments': typeof assistingLawyersAssistingDashboardPaymentsRoute
  '/assisting-dashboard/profile': typeof assistingLawyersAssistingDashboardProfileRoute
  '/assisting-dashboard/proposals': typeof assistingLawyersAssistingDashboardProposalsRoute
  '/engaging-dashboard/messages': typeof engagingLaywersEngagingDashboardMessagesRouteWithChildren
  '/engaging-dashboard/notifications': typeof engagingLaywersEngagingDashboardNotificationsRoute
  '/engaging-dashboard/payments': typeof engagingLaywersEngagingDashboardPaymentsRoute
  '/engaging-dashboard/post-job': typeof engagingLaywersEngagingDashboardPostJobRoute
  '/engaging-dashboard/ratings': typeof engagingLaywersEngagingDashboardRatingsRoute
  '/engaging-dashboard/settings': typeof engagingLaywersEngagingDashboardSettingsRoute
  '/admin-dashboard/': typeof adminAdminDashboardIndexRoute
  '/assisting-dashboard/': typeof assistingLawyersAssistingDashboardIndexRoute
  '/engaging-dashboard/': typeof engagingLaywersEngagingDashboardIndexRoute
  '/admin-dashboard/lawyers/$lawyerId': typeof adminAdminDashboardLawyersLawyerIdRoute
  '/admin-dashboard/tasks/$taskId': typeof adminAdminDashboardTasksTaskIdRoute
  '/assisting-dashboard/apply/$taskId': typeof assistingLawyersAssistingDashboardApplyTaskIdRoute
  '/assisting-dashboard/messages/$taskId': typeof assistingLawyersAssistingDashboardMessagesTaskIdRoute
  '/assisting-dashboard/request-sent/$taskId': typeof assistingLawyersAssistingDashboardRequestSentTaskIdRoute
  '/assisting-dashboard/task/$taskId': typeof assistingLawyersAssistingDashboardTaskTaskIdRoute
  '/engaging-dashboard/fund-task/$taskId': typeof engagingLaywersEngagingDashboardFundTaskTaskIdRoute
  '/engaging-dashboard/messages/$taskId': typeof engagingLaywersEngagingDashboardMessagesTaskIdRoute
  '/engaging-dashboard/review-proposals/$taskId': typeof engagingLaywersEngagingDashboardReviewProposalsTaskIdRoute
  '/engaging-dashboard/review-work/$taskId': typeof engagingLaywersEngagingDashboardReviewWorkTaskIdRoute
  '/engaging-dashboard/submit-rating/$taskId': typeof engagingLaywersEngagingDashboardSubmitRatingTaskIdRoute
  '/engaging-dashboard/your-rating/$taskId': typeof engagingLaywersEngagingDashboardYourRatingTaskIdRoute
  '/admin-dashboard/lawyers/': typeof adminAdminDashboardLawyersIndexRoute
  '/admin-dashboard/tasks/': typeof adminAdminDashboardTasksIndexRoute
  '/auth/login/': typeof engagingLaywersAuthLoginIndexRoute
  '/auth/register/': typeof engagingLaywersAuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof landingpageIndexRoute
  '/admin-dashboard/announcements': typeof adminAdminDashboardAnnouncementsRoute
  '/admin-dashboard/finance': typeof adminAdminDashboardFinanceRoute
  '/admin-dashboard/report': typeof adminAdminDashboardReportRoute
  '/admin-dashboard/roles': typeof adminAdminDashboardRolesRoute
  '/assisting-dashboard/messages': typeof assistingLawyersAssistingDashboardMessagesRouteWithChildren
  '/assisting-dashboard/notifications': typeof assistingLawyersAssistingDashboardNotificationsRoute
  '/assisting-dashboard/payments': typeof assistingLawyersAssistingDashboardPaymentsRoute
  '/assisting-dashboard/profile': typeof assistingLawyersAssistingDashboardProfileRoute
  '/assisting-dashboard/proposals': typeof assistingLawyersAssistingDashboardProposalsRoute
  '/engaging-dashboard/messages': typeof engagingLaywersEngagingDashboardMessagesRouteWithChildren
  '/engaging-dashboard/notifications': typeof engagingLaywersEngagingDashboardNotificationsRoute
  '/engaging-dashboard/payments': typeof engagingLaywersEngagingDashboardPaymentsRoute
  '/engaging-dashboard/post-job': typeof engagingLaywersEngagingDashboardPostJobRoute
  '/engaging-dashboard/ratings': typeof engagingLaywersEngagingDashboardRatingsRoute
  '/engaging-dashboard/settings': typeof engagingLaywersEngagingDashboardSettingsRoute
  '/admin-dashboard': typeof adminAdminDashboardIndexRoute
  '/assisting-dashboard': typeof assistingLawyersAssistingDashboardIndexRoute
  '/engaging-dashboard': typeof engagingLaywersEngagingDashboardIndexRoute
  '/admin-dashboard/lawyers/$lawyerId': typeof adminAdminDashboardLawyersLawyerIdRoute
  '/admin-dashboard/tasks/$taskId': typeof adminAdminDashboardTasksTaskIdRoute
  '/assisting-dashboard/apply/$taskId': typeof assistingLawyersAssistingDashboardApplyTaskIdRoute
  '/assisting-dashboard/messages/$taskId': typeof assistingLawyersAssistingDashboardMessagesTaskIdRoute
  '/assisting-dashboard/request-sent/$taskId': typeof assistingLawyersAssistingDashboardRequestSentTaskIdRoute
  '/assisting-dashboard/task/$taskId': typeof assistingLawyersAssistingDashboardTaskTaskIdRoute
  '/engaging-dashboard/fund-task/$taskId': typeof engagingLaywersEngagingDashboardFundTaskTaskIdRoute
  '/engaging-dashboard/messages/$taskId': typeof engagingLaywersEngagingDashboardMessagesTaskIdRoute
  '/engaging-dashboard/review-proposals/$taskId': typeof engagingLaywersEngagingDashboardReviewProposalsTaskIdRoute
  '/engaging-dashboard/review-work/$taskId': typeof engagingLaywersEngagingDashboardReviewWorkTaskIdRoute
  '/engaging-dashboard/submit-rating/$taskId': typeof engagingLaywersEngagingDashboardSubmitRatingTaskIdRoute
  '/engaging-dashboard/your-rating/$taskId': typeof engagingLaywersEngagingDashboardYourRatingTaskIdRoute
  '/admin-dashboard/lawyers': typeof adminAdminDashboardLawyersIndexRoute
  '/admin-dashboard/tasks': typeof adminAdminDashboardTasksIndexRoute
  '/auth/login': typeof engagingLaywersAuthLoginIndexRoute
  '/auth/register': typeof engagingLaywersAuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)/admin-dashboard': typeof adminAdminDashboardRouteWithChildren
  '/(assisting-lawyers)/assisting-dashboard': typeof assistingLawyersAssistingDashboardRouteWithChildren
  '/(engaging-laywers)/engaging-dashboard': typeof engagingLaywersEngagingDashboardRouteWithChildren
  '/(landingpage)/': typeof landingpageIndexRoute
  '/(admin)/admin-dashboard/announcements': typeof adminAdminDashboardAnnouncementsRoute
  '/(admin)/admin-dashboard/finance': typeof adminAdminDashboardFinanceRoute
  '/(admin)/admin-dashboard/lawyers': typeof adminAdminDashboardLawyersRouteWithChildren
  '/(admin)/admin-dashboard/report': typeof adminAdminDashboardReportRoute
  '/(admin)/admin-dashboard/roles': typeof adminAdminDashboardRolesRoute
  '/(admin)/admin-dashboard/tasks': typeof adminAdminDashboardTasksRouteWithChildren
  '/(assisting-lawyers)/assisting-dashboard/messages': typeof assistingLawyersAssistingDashboardMessagesRouteWithChildren
  '/(assisting-lawyers)/assisting-dashboard/notifications': typeof assistingLawyersAssistingDashboardNotificationsRoute
  '/(assisting-lawyers)/assisting-dashboard/payments': typeof assistingLawyersAssistingDashboardPaymentsRoute
  '/(assisting-lawyers)/assisting-dashboard/profile': typeof assistingLawyersAssistingDashboardProfileRoute
  '/(assisting-lawyers)/assisting-dashboard/proposals': typeof assistingLawyersAssistingDashboardProposalsRoute
  '/(engaging-laywers)/engaging-dashboard/messages': typeof engagingLaywersEngagingDashboardMessagesRouteWithChildren
  '/(engaging-laywers)/engaging-dashboard/notifications': typeof engagingLaywersEngagingDashboardNotificationsRoute
  '/(engaging-laywers)/engaging-dashboard/payments': typeof engagingLaywersEngagingDashboardPaymentsRoute
  '/(engaging-laywers)/engaging-dashboard/post-job': typeof engagingLaywersEngagingDashboardPostJobRoute
  '/(engaging-laywers)/engaging-dashboard/ratings': typeof engagingLaywersEngagingDashboardRatingsRoute
  '/(engaging-laywers)/engaging-dashboard/settings': typeof engagingLaywersEngagingDashboardSettingsRoute
  '/(admin)/admin-dashboard/': typeof adminAdminDashboardIndexRoute
  '/(assisting-lawyers)/assisting-dashboard/': typeof assistingLawyersAssistingDashboardIndexRoute
  '/(engaging-laywers)/engaging-dashboard/': typeof engagingLaywersEngagingDashboardIndexRoute
  '/(admin)/admin-dashboard/lawyers/$lawyerId': typeof adminAdminDashboardLawyersLawyerIdRoute
  '/(admin)/admin-dashboard/tasks/$taskId': typeof adminAdminDashboardTasksTaskIdRoute
  '/(assisting-lawyers)/assisting-dashboard/apply/$taskId': typeof assistingLawyersAssistingDashboardApplyTaskIdRoute
  '/(assisting-lawyers)/assisting-dashboard/messages/$taskId': typeof assistingLawyersAssistingDashboardMessagesTaskIdRoute
  '/(assisting-lawyers)/assisting-dashboard/request-sent/$taskId': typeof assistingLawyersAssistingDashboardRequestSentTaskIdRoute
  '/(assisting-lawyers)/assisting-dashboard/task/$taskId': typeof assistingLawyersAssistingDashboardTaskTaskIdRoute
  '/(engaging-laywers)/engaging-dashboard/fund-task/$taskId': typeof engagingLaywersEngagingDashboardFundTaskTaskIdRoute
  '/(engaging-laywers)/engaging-dashboard/messages/$taskId': typeof engagingLaywersEngagingDashboardMessagesTaskIdRoute
  '/(engaging-laywers)/engaging-dashboard/review-proposals/$taskId': typeof engagingLaywersEngagingDashboardReviewProposalsTaskIdRoute
  '/(engaging-laywers)/engaging-dashboard/review-work/$taskId': typeof engagingLaywersEngagingDashboardReviewWorkTaskIdRoute
  '/(engaging-laywers)/engaging-dashboard/submit-rating/$taskId': typeof engagingLaywersEngagingDashboardSubmitRatingTaskIdRoute
  '/(engaging-laywers)/engaging-dashboard/your-rating/$taskId': typeof engagingLaywersEngagingDashboardYourRatingTaskIdRoute
  '/(admin)/admin-dashboard/lawyers/': typeof adminAdminDashboardLawyersIndexRoute
  '/(admin)/admin-dashboard/tasks/': typeof adminAdminDashboardTasksIndexRoute
  '/(engaging-laywers)/auth/login/': typeof engagingLaywersAuthLoginIndexRoute
  '/(engaging-laywers)/auth/register/': typeof engagingLaywersAuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin-dashboard'
    | '/assisting-dashboard'
    | '/engaging-dashboard'
    | '/'
    | '/admin-dashboard/announcements'
    | '/admin-dashboard/finance'
    | '/admin-dashboard/lawyers'
    | '/admin-dashboard/report'
    | '/admin-dashboard/roles'
    | '/admin-dashboard/tasks'
    | '/assisting-dashboard/messages'
    | '/assisting-dashboard/notifications'
    | '/assisting-dashboard/payments'
    | '/assisting-dashboard/profile'
    | '/assisting-dashboard/proposals'
    | '/engaging-dashboard/messages'
    | '/engaging-dashboard/notifications'
    | '/engaging-dashboard/payments'
    | '/engaging-dashboard/post-job'
    | '/engaging-dashboard/ratings'
    | '/engaging-dashboard/settings'
    | '/admin-dashboard/'
    | '/assisting-dashboard/'
    | '/engaging-dashboard/'
    | '/admin-dashboard/lawyers/$lawyerId'
    | '/admin-dashboard/tasks/$taskId'
    | '/assisting-dashboard/apply/$taskId'
    | '/assisting-dashboard/messages/$taskId'
    | '/assisting-dashboard/request-sent/$taskId'
    | '/assisting-dashboard/task/$taskId'
    | '/engaging-dashboard/fund-task/$taskId'
    | '/engaging-dashboard/messages/$taskId'
    | '/engaging-dashboard/review-proposals/$taskId'
    | '/engaging-dashboard/review-work/$taskId'
    | '/engaging-dashboard/submit-rating/$taskId'
    | '/engaging-dashboard/your-rating/$taskId'
    | '/admin-dashboard/lawyers/'
    | '/admin-dashboard/tasks/'
    | '/auth/login/'
    | '/auth/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard/announcements'
    | '/admin-dashboard/finance'
    | '/admin-dashboard/report'
    | '/admin-dashboard/roles'
    | '/assisting-dashboard/messages'
    | '/assisting-dashboard/notifications'
    | '/assisting-dashboard/payments'
    | '/assisting-dashboard/profile'
    | '/assisting-dashboard/proposals'
    | '/engaging-dashboard/messages'
    | '/engaging-dashboard/notifications'
    | '/engaging-dashboard/payments'
    | '/engaging-dashboard/post-job'
    | '/engaging-dashboard/ratings'
    | '/engaging-dashboard/settings'
    | '/admin-dashboard'
    | '/assisting-dashboard'
    | '/engaging-dashboard'
    | '/admin-dashboard/lawyers/$lawyerId'
    | '/admin-dashboard/tasks/$taskId'
    | '/assisting-dashboard/apply/$taskId'
    | '/assisting-dashboard/messages/$taskId'
    | '/assisting-dashboard/request-sent/$taskId'
    | '/assisting-dashboard/task/$taskId'
    | '/engaging-dashboard/fund-task/$taskId'
    | '/engaging-dashboard/messages/$taskId'
    | '/engaging-dashboard/review-proposals/$taskId'
    | '/engaging-dashboard/review-work/$taskId'
    | '/engaging-dashboard/submit-rating/$taskId'
    | '/engaging-dashboard/your-rating/$taskId'
    | '/admin-dashboard/lawyers'
    | '/admin-dashboard/tasks'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/(admin)/admin-dashboard'
    | '/(assisting-lawyers)/assisting-dashboard'
    | '/(engaging-laywers)/engaging-dashboard'
    | '/(landingpage)/'
    | '/(admin)/admin-dashboard/announcements'
    | '/(admin)/admin-dashboard/finance'
    | '/(admin)/admin-dashboard/lawyers'
    | '/(admin)/admin-dashboard/report'
    | '/(admin)/admin-dashboard/roles'
    | '/(admin)/admin-dashboard/tasks'
    | '/(assisting-lawyers)/assisting-dashboard/messages'
    | '/(assisting-lawyers)/assisting-dashboard/notifications'
    | '/(assisting-lawyers)/assisting-dashboard/payments'
    | '/(assisting-lawyers)/assisting-dashboard/profile'
    | '/(assisting-lawyers)/assisting-dashboard/proposals'
    | '/(engaging-laywers)/engaging-dashboard/messages'
    | '/(engaging-laywers)/engaging-dashboard/notifications'
    | '/(engaging-laywers)/engaging-dashboard/payments'
    | '/(engaging-laywers)/engaging-dashboard/post-job'
    | '/(engaging-laywers)/engaging-dashboard/ratings'
    | '/(engaging-laywers)/engaging-dashboard/settings'
    | '/(admin)/admin-dashboard/'
    | '/(assisting-lawyers)/assisting-dashboard/'
    | '/(engaging-laywers)/engaging-dashboard/'
    | '/(admin)/admin-dashboard/lawyers/$lawyerId'
    | '/(admin)/admin-dashboard/tasks/$taskId'
    | '/(assisting-lawyers)/assisting-dashboard/apply/$taskId'
    | '/(assisting-lawyers)/assisting-dashboard/messages/$taskId'
    | '/(assisting-lawyers)/assisting-dashboard/request-sent/$taskId'
    | '/(assisting-lawyers)/assisting-dashboard/task/$taskId'
    | '/(engaging-laywers)/engaging-dashboard/fund-task/$taskId'
    | '/(engaging-laywers)/engaging-dashboard/messages/$taskId'
    | '/(engaging-laywers)/engaging-dashboard/review-proposals/$taskId'
    | '/(engaging-laywers)/engaging-dashboard/review-work/$taskId'
    | '/(engaging-laywers)/engaging-dashboard/submit-rating/$taskId'
    | '/(engaging-laywers)/engaging-dashboard/your-rating/$taskId'
    | '/(admin)/admin-dashboard/lawyers/'
    | '/(admin)/admin-dashboard/tasks/'
    | '/(engaging-laywers)/auth/login/'
    | '/(engaging-laywers)/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminAdminDashboardRoute: typeof adminAdminDashboardRouteWithChildren
  assistingLawyersAssistingDashboardRoute: typeof assistingLawyersAssistingDashboardRouteWithChildren
  engagingLaywersEngagingDashboardRoute: typeof engagingLaywersEngagingDashboardRouteWithChildren
  landingpageIndexRoute: typeof landingpageIndexRoute
  engagingLaywersAuthLoginIndexRoute: typeof engagingLaywersAuthLoginIndexRoute
  engagingLaywersAuthRegisterIndexRoute: typeof engagingLaywersAuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(admin)/admin-dashboard': {
      id: '/(admin)/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof adminAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(assisting-lawyers)/assisting-dashboard': {
      id: '/(assisting-lawyers)/assisting-dashboard'
      path: '/assisting-dashboard'
      fullPath: '/assisting-dashboard'
      preLoaderRoute: typeof assistingLawyersAssistingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(engaging-laywers)/engaging-dashboard': {
      id: '/(engaging-laywers)/engaging-dashboard'
      path: '/engaging-dashboard'
      fullPath: '/engaging-dashboard'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landingpage)/': {
      id: '/(landingpage)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingpageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/admin-dashboard/': {
      id: '/(admin)/admin-dashboard/'
      path: '/'
      fullPath: '/admin-dashboard/'
      preLoaderRoute: typeof adminAdminDashboardIndexRouteImport
      parentRoute: typeof adminAdminDashboardRoute
    }
    '/(admin)/admin-dashboard/announcements': {
      id: '/(admin)/admin-dashboard/announcements'
      path: '/announcements'
      fullPath: '/admin-dashboard/announcements'
      preLoaderRoute: typeof adminAdminDashboardAnnouncementsRouteImport
      parentRoute: typeof adminAdminDashboardRoute
    }
    '/(admin)/admin-dashboard/finance': {
      id: '/(admin)/admin-dashboard/finance'
      path: '/finance'
      fullPath: '/admin-dashboard/finance'
      preLoaderRoute: typeof adminAdminDashboardFinanceRouteImport
      parentRoute: typeof adminAdminDashboardRoute
    }
    '/(admin)/admin-dashboard/lawyers': {
      id: '/(admin)/admin-dashboard/lawyers'
      path: '/lawyers'
      fullPath: '/admin-dashboard/lawyers'
      preLoaderRoute: typeof adminAdminDashboardLawyersRouteImport
      parentRoute: typeof adminAdminDashboardRoute
    }
    '/(admin)/admin-dashboard/report': {
      id: '/(admin)/admin-dashboard/report'
      path: '/report'
      fullPath: '/admin-dashboard/report'
      preLoaderRoute: typeof adminAdminDashboardReportRouteImport
      parentRoute: typeof adminAdminDashboardRoute
    }
    '/(admin)/admin-dashboard/roles': {
      id: '/(admin)/admin-dashboard/roles'
      path: '/roles'
      fullPath: '/admin-dashboard/roles'
      preLoaderRoute: typeof adminAdminDashboardRolesRouteImport
      parentRoute: typeof adminAdminDashboardRoute
    }
    '/(admin)/admin-dashboard/tasks': {
      id: '/(admin)/admin-dashboard/tasks'
      path: '/tasks'
      fullPath: '/admin-dashboard/tasks'
      preLoaderRoute: typeof adminAdminDashboardTasksRouteImport
      parentRoute: typeof adminAdminDashboardRoute
    }
    '/(assisting-lawyers)/assisting-dashboard/': {
      id: '/(assisting-lawyers)/assisting-dashboard/'
      path: '/'
      fullPath: '/assisting-dashboard/'
      preLoaderRoute: typeof assistingLawyersAssistingDashboardIndexRouteImport
      parentRoute: typeof assistingLawyersAssistingDashboardRoute
    }
    '/(assisting-lawyers)/assisting-dashboard/messages': {
      id: '/(assisting-lawyers)/assisting-dashboard/messages'
      path: '/messages'
      fullPath: '/assisting-dashboard/messages'
      preLoaderRoute: typeof assistingLawyersAssistingDashboardMessagesRouteImport
      parentRoute: typeof assistingLawyersAssistingDashboardRoute
    }
    '/(assisting-lawyers)/assisting-dashboard/notifications': {
      id: '/(assisting-lawyers)/assisting-dashboard/notifications'
      path: '/notifications'
      fullPath: '/assisting-dashboard/notifications'
      preLoaderRoute: typeof assistingLawyersAssistingDashboardNotificationsRouteImport
      parentRoute: typeof assistingLawyersAssistingDashboardRoute
    }
    '/(assisting-lawyers)/assisting-dashboard/payments': {
      id: '/(assisting-lawyers)/assisting-dashboard/payments'
      path: '/payments'
      fullPath: '/assisting-dashboard/payments'
      preLoaderRoute: typeof assistingLawyersAssistingDashboardPaymentsRouteImport
      parentRoute: typeof assistingLawyersAssistingDashboardRoute
    }
    '/(assisting-lawyers)/assisting-dashboard/profile': {
      id: '/(assisting-lawyers)/assisting-dashboard/profile'
      path: '/profile'
      fullPath: '/assisting-dashboard/profile'
      preLoaderRoute: typeof assistingLawyersAssistingDashboardProfileRouteImport
      parentRoute: typeof assistingLawyersAssistingDashboardRoute
    }
    '/(assisting-lawyers)/assisting-dashboard/proposals': {
      id: '/(assisting-lawyers)/assisting-dashboard/proposals'
      path: '/proposals'
      fullPath: '/assisting-dashboard/proposals'
      preLoaderRoute: typeof assistingLawyersAssistingDashboardProposalsRouteImport
      parentRoute: typeof assistingLawyersAssistingDashboardRoute
    }
    '/(engaging-laywers)/engaging-dashboard/': {
      id: '/(engaging-laywers)/engaging-dashboard/'
      path: '/'
      fullPath: '/engaging-dashboard/'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardIndexRouteImport
      parentRoute: typeof engagingLaywersEngagingDashboardRoute
    }
    '/(engaging-laywers)/engaging-dashboard/messages': {
      id: '/(engaging-laywers)/engaging-dashboard/messages'
      path: '/messages'
      fullPath: '/engaging-dashboard/messages'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardMessagesRouteImport
      parentRoute: typeof engagingLaywersEngagingDashboardRoute
    }
    '/(engaging-laywers)/engaging-dashboard/notifications': {
      id: '/(engaging-laywers)/engaging-dashboard/notifications'
      path: '/notifications'
      fullPath: '/engaging-dashboard/notifications'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardNotificationsRouteImport
      parentRoute: typeof engagingLaywersEngagingDashboardRoute
    }
    '/(engaging-laywers)/engaging-dashboard/payments': {
      id: '/(engaging-laywers)/engaging-dashboard/payments'
      path: '/payments'
      fullPath: '/engaging-dashboard/payments'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardPaymentsRouteImport
      parentRoute: typeof engagingLaywersEngagingDashboardRoute
    }
    '/(engaging-laywers)/engaging-dashboard/post-job': {
      id: '/(engaging-laywers)/engaging-dashboard/post-job'
      path: '/post-job'
      fullPath: '/engaging-dashboard/post-job'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardPostJobRouteImport
      parentRoute: typeof engagingLaywersEngagingDashboardRoute
    }
    '/(engaging-laywers)/engaging-dashboard/ratings': {
      id: '/(engaging-laywers)/engaging-dashboard/ratings'
      path: '/ratings'
      fullPath: '/engaging-dashboard/ratings'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardRatingsRouteImport
      parentRoute: typeof engagingLaywersEngagingDashboardRoute
    }
    '/(engaging-laywers)/engaging-dashboard/settings': {
      id: '/(engaging-laywers)/engaging-dashboard/settings'
      path: '/settings'
      fullPath: '/engaging-dashboard/settings'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardSettingsRouteImport
      parentRoute: typeof engagingLaywersEngagingDashboardRoute
    }
    '/(admin)/admin-dashboard/lawyers/': {
      id: '/(admin)/admin-dashboard/lawyers/'
      path: '/'
      fullPath: '/admin-dashboard/lawyers/'
      preLoaderRoute: typeof adminAdminDashboardLawyersIndexRouteImport
      parentRoute: typeof adminAdminDashboardLawyersRoute
    }
    '/(admin)/admin-dashboard/lawyers/$lawyerId': {
      id: '/(admin)/admin-dashboard/lawyers/$lawyerId'
      path: '/$lawyerId'
      fullPath: '/admin-dashboard/lawyers/$lawyerId'
      preLoaderRoute: typeof adminAdminDashboardLawyersLawyerIdRouteImport
      parentRoute: typeof adminAdminDashboardLawyersRoute
    }
    '/(admin)/admin-dashboard/tasks/': {
      id: '/(admin)/admin-dashboard/tasks/'
      path: '/'
      fullPath: '/admin-dashboard/tasks/'
      preLoaderRoute: typeof adminAdminDashboardTasksIndexRouteImport
      parentRoute: typeof adminAdminDashboardTasksRoute
    }
    '/(admin)/admin-dashboard/tasks/$taskId': {
      id: '/(admin)/admin-dashboard/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/admin-dashboard/tasks/$taskId'
      preLoaderRoute: typeof adminAdminDashboardTasksTaskIdRouteImport
      parentRoute: typeof adminAdminDashboardTasksRoute
    }
    '/(assisting-lawyers)/assisting-dashboard/apply/$taskId': {
      id: '/(assisting-lawyers)/assisting-dashboard/apply/$taskId'
      path: '/apply/$taskId'
      fullPath: '/assisting-dashboard/apply/$taskId'
      preLoaderRoute: typeof assistingLawyersAssistingDashboardApplyTaskIdRouteImport
      parentRoute: typeof assistingLawyersAssistingDashboardRoute
    }
    '/(assisting-lawyers)/assisting-dashboard/messages/$taskId': {
      id: '/(assisting-lawyers)/assisting-dashboard/messages/$taskId'
      path: '/$taskId'
      fullPath: '/assisting-dashboard/messages/$taskId'
      preLoaderRoute: typeof assistingLawyersAssistingDashboardMessagesTaskIdRouteImport
      parentRoute: typeof assistingLawyersAssistingDashboardMessagesRoute
    }
    '/(assisting-lawyers)/assisting-dashboard/request-sent/$taskId': {
      id: '/(assisting-lawyers)/assisting-dashboard/request-sent/$taskId'
      path: '/request-sent/$taskId'
      fullPath: '/assisting-dashboard/request-sent/$taskId'
      preLoaderRoute: typeof assistingLawyersAssistingDashboardRequestSentTaskIdRouteImport
      parentRoute: typeof assistingLawyersAssistingDashboardRoute
    }
    '/(assisting-lawyers)/assisting-dashboard/task/$taskId': {
      id: '/(assisting-lawyers)/assisting-dashboard/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/assisting-dashboard/task/$taskId'
      preLoaderRoute: typeof assistingLawyersAssistingDashboardTaskTaskIdRouteImport
      parentRoute: typeof assistingLawyersAssistingDashboardRoute
    }
    '/(engaging-laywers)/auth/login/': {
      id: '/(engaging-laywers)/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof engagingLaywersAuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(engaging-laywers)/auth/register/': {
      id: '/(engaging-laywers)/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof engagingLaywersAuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(engaging-laywers)/engaging-dashboard/fund-task/$taskId': {
      id: '/(engaging-laywers)/engaging-dashboard/fund-task/$taskId'
      path: '/fund-task/$taskId'
      fullPath: '/engaging-dashboard/fund-task/$taskId'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardFundTaskTaskIdRouteImport
      parentRoute: typeof engagingLaywersEngagingDashboardRoute
    }
    '/(engaging-laywers)/engaging-dashboard/messages/$taskId': {
      id: '/(engaging-laywers)/engaging-dashboard/messages/$taskId'
      path: '/$taskId'
      fullPath: '/engaging-dashboard/messages/$taskId'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardMessagesTaskIdRouteImport
      parentRoute: typeof engagingLaywersEngagingDashboardMessagesRoute
    }
    '/(engaging-laywers)/engaging-dashboard/review-proposals/$taskId': {
      id: '/(engaging-laywers)/engaging-dashboard/review-proposals/$taskId'
      path: '/review-proposals/$taskId'
      fullPath: '/engaging-dashboard/review-proposals/$taskId'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardReviewProposalsTaskIdRouteImport
      parentRoute: typeof engagingLaywersEngagingDashboardRoute
    }
    '/(engaging-laywers)/engaging-dashboard/review-work/$taskId': {
      id: '/(engaging-laywers)/engaging-dashboard/review-work/$taskId'
      path: '/review-work/$taskId'
      fullPath: '/engaging-dashboard/review-work/$taskId'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardReviewWorkTaskIdRouteImport
      parentRoute: typeof engagingLaywersEngagingDashboardRoute
    }
    '/(engaging-laywers)/engaging-dashboard/submit-rating/$taskId': {
      id: '/(engaging-laywers)/engaging-dashboard/submit-rating/$taskId'
      path: '/submit-rating/$taskId'
      fullPath: '/engaging-dashboard/submit-rating/$taskId'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardSubmitRatingTaskIdRouteImport
      parentRoute: typeof engagingLaywersEngagingDashboardRoute
    }
    '/(engaging-laywers)/engaging-dashboard/your-rating/$taskId': {
      id: '/(engaging-laywers)/engaging-dashboard/your-rating/$taskId'
      path: '/your-rating/$taskId'
      fullPath: '/engaging-dashboard/your-rating/$taskId'
      preLoaderRoute: typeof engagingLaywersEngagingDashboardYourRatingTaskIdRouteImport
      parentRoute: typeof engagingLaywersEngagingDashboardRoute
    }
  }
}

interface adminAdminDashboardLawyersRouteChildren {
  adminAdminDashboardLawyersLawyerIdRoute: typeof adminAdminDashboardLawyersLawyerIdRoute
  adminAdminDashboardLawyersIndexRoute: typeof adminAdminDashboardLawyersIndexRoute
}

const adminAdminDashboardLawyersRouteChildren: adminAdminDashboardLawyersRouteChildren =
  {
    adminAdminDashboardLawyersLawyerIdRoute:
      adminAdminDashboardLawyersLawyerIdRoute,
    adminAdminDashboardLawyersIndexRoute: adminAdminDashboardLawyersIndexRoute,
  }

const adminAdminDashboardLawyersRouteWithChildren =
  adminAdminDashboardLawyersRoute._addFileChildren(
    adminAdminDashboardLawyersRouteChildren,
  )

interface adminAdminDashboardTasksRouteChildren {
  adminAdminDashboardTasksTaskIdRoute: typeof adminAdminDashboardTasksTaskIdRoute
  adminAdminDashboardTasksIndexRoute: typeof adminAdminDashboardTasksIndexRoute
}

const adminAdminDashboardTasksRouteChildren: adminAdminDashboardTasksRouteChildren =
  {
    adminAdminDashboardTasksTaskIdRoute: adminAdminDashboardTasksTaskIdRoute,
    adminAdminDashboardTasksIndexRoute: adminAdminDashboardTasksIndexRoute,
  }

const adminAdminDashboardTasksRouteWithChildren =
  adminAdminDashboardTasksRoute._addFileChildren(
    adminAdminDashboardTasksRouteChildren,
  )

interface adminAdminDashboardRouteChildren {
  adminAdminDashboardAnnouncementsRoute: typeof adminAdminDashboardAnnouncementsRoute
  adminAdminDashboardFinanceRoute: typeof adminAdminDashboardFinanceRoute
  adminAdminDashboardLawyersRoute: typeof adminAdminDashboardLawyersRouteWithChildren
  adminAdminDashboardReportRoute: typeof adminAdminDashboardReportRoute
  adminAdminDashboardRolesRoute: typeof adminAdminDashboardRolesRoute
  adminAdminDashboardTasksRoute: typeof adminAdminDashboardTasksRouteWithChildren
  adminAdminDashboardIndexRoute: typeof adminAdminDashboardIndexRoute
}

const adminAdminDashboardRouteChildren: adminAdminDashboardRouteChildren = {
  adminAdminDashboardAnnouncementsRoute: adminAdminDashboardAnnouncementsRoute,
  adminAdminDashboardFinanceRoute: adminAdminDashboardFinanceRoute,
  adminAdminDashboardLawyersRoute: adminAdminDashboardLawyersRouteWithChildren,
  adminAdminDashboardReportRoute: adminAdminDashboardReportRoute,
  adminAdminDashboardRolesRoute: adminAdminDashboardRolesRoute,
  adminAdminDashboardTasksRoute: adminAdminDashboardTasksRouteWithChildren,
  adminAdminDashboardIndexRoute: adminAdminDashboardIndexRoute,
}

const adminAdminDashboardRouteWithChildren =
  adminAdminDashboardRoute._addFileChildren(adminAdminDashboardRouteChildren)

interface assistingLawyersAssistingDashboardMessagesRouteChildren {
  assistingLawyersAssistingDashboardMessagesTaskIdRoute: typeof assistingLawyersAssistingDashboardMessagesTaskIdRoute
}

const assistingLawyersAssistingDashboardMessagesRouteChildren: assistingLawyersAssistingDashboardMessagesRouteChildren =
  {
    assistingLawyersAssistingDashboardMessagesTaskIdRoute:
      assistingLawyersAssistingDashboardMessagesTaskIdRoute,
  }

const assistingLawyersAssistingDashboardMessagesRouteWithChildren =
  assistingLawyersAssistingDashboardMessagesRoute._addFileChildren(
    assistingLawyersAssistingDashboardMessagesRouteChildren,
  )

interface assistingLawyersAssistingDashboardRouteChildren {
  assistingLawyersAssistingDashboardMessagesRoute: typeof assistingLawyersAssistingDashboardMessagesRouteWithChildren
  assistingLawyersAssistingDashboardNotificationsRoute: typeof assistingLawyersAssistingDashboardNotificationsRoute
  assistingLawyersAssistingDashboardPaymentsRoute: typeof assistingLawyersAssistingDashboardPaymentsRoute
  assistingLawyersAssistingDashboardProfileRoute: typeof assistingLawyersAssistingDashboardProfileRoute
  assistingLawyersAssistingDashboardProposalsRoute: typeof assistingLawyersAssistingDashboardProposalsRoute
  assistingLawyersAssistingDashboardIndexRoute: typeof assistingLawyersAssistingDashboardIndexRoute
  assistingLawyersAssistingDashboardApplyTaskIdRoute: typeof assistingLawyersAssistingDashboardApplyTaskIdRoute
  assistingLawyersAssistingDashboardRequestSentTaskIdRoute: typeof assistingLawyersAssistingDashboardRequestSentTaskIdRoute
  assistingLawyersAssistingDashboardTaskTaskIdRoute: typeof assistingLawyersAssistingDashboardTaskTaskIdRoute
}

const assistingLawyersAssistingDashboardRouteChildren: assistingLawyersAssistingDashboardRouteChildren =
  {
    assistingLawyersAssistingDashboardMessagesRoute:
      assistingLawyersAssistingDashboardMessagesRouteWithChildren,
    assistingLawyersAssistingDashboardNotificationsRoute:
      assistingLawyersAssistingDashboardNotificationsRoute,
    assistingLawyersAssistingDashboardPaymentsRoute:
      assistingLawyersAssistingDashboardPaymentsRoute,
    assistingLawyersAssistingDashboardProfileRoute:
      assistingLawyersAssistingDashboardProfileRoute,
    assistingLawyersAssistingDashboardProposalsRoute:
      assistingLawyersAssistingDashboardProposalsRoute,
    assistingLawyersAssistingDashboardIndexRoute:
      assistingLawyersAssistingDashboardIndexRoute,
    assistingLawyersAssistingDashboardApplyTaskIdRoute:
      assistingLawyersAssistingDashboardApplyTaskIdRoute,
    assistingLawyersAssistingDashboardRequestSentTaskIdRoute:
      assistingLawyersAssistingDashboardRequestSentTaskIdRoute,
    assistingLawyersAssistingDashboardTaskTaskIdRoute:
      assistingLawyersAssistingDashboardTaskTaskIdRoute,
  }

const assistingLawyersAssistingDashboardRouteWithChildren =
  assistingLawyersAssistingDashboardRoute._addFileChildren(
    assistingLawyersAssistingDashboardRouteChildren,
  )

interface engagingLaywersEngagingDashboardMessagesRouteChildren {
  engagingLaywersEngagingDashboardMessagesTaskIdRoute: typeof engagingLaywersEngagingDashboardMessagesTaskIdRoute
}

const engagingLaywersEngagingDashboardMessagesRouteChildren: engagingLaywersEngagingDashboardMessagesRouteChildren =
  {
    engagingLaywersEngagingDashboardMessagesTaskIdRoute:
      engagingLaywersEngagingDashboardMessagesTaskIdRoute,
  }

const engagingLaywersEngagingDashboardMessagesRouteWithChildren =
  engagingLaywersEngagingDashboardMessagesRoute._addFileChildren(
    engagingLaywersEngagingDashboardMessagesRouteChildren,
  )

interface engagingLaywersEngagingDashboardRouteChildren {
  engagingLaywersEngagingDashboardMessagesRoute: typeof engagingLaywersEngagingDashboardMessagesRouteWithChildren
  engagingLaywersEngagingDashboardNotificationsRoute: typeof engagingLaywersEngagingDashboardNotificationsRoute
  engagingLaywersEngagingDashboardPaymentsRoute: typeof engagingLaywersEngagingDashboardPaymentsRoute
  engagingLaywersEngagingDashboardPostJobRoute: typeof engagingLaywersEngagingDashboardPostJobRoute
  engagingLaywersEngagingDashboardRatingsRoute: typeof engagingLaywersEngagingDashboardRatingsRoute
  engagingLaywersEngagingDashboardSettingsRoute: typeof engagingLaywersEngagingDashboardSettingsRoute
  engagingLaywersEngagingDashboardIndexRoute: typeof engagingLaywersEngagingDashboardIndexRoute
  engagingLaywersEngagingDashboardFundTaskTaskIdRoute: typeof engagingLaywersEngagingDashboardFundTaskTaskIdRoute
  engagingLaywersEngagingDashboardReviewProposalsTaskIdRoute: typeof engagingLaywersEngagingDashboardReviewProposalsTaskIdRoute
  engagingLaywersEngagingDashboardReviewWorkTaskIdRoute: typeof engagingLaywersEngagingDashboardReviewWorkTaskIdRoute
  engagingLaywersEngagingDashboardSubmitRatingTaskIdRoute: typeof engagingLaywersEngagingDashboardSubmitRatingTaskIdRoute
  engagingLaywersEngagingDashboardYourRatingTaskIdRoute: typeof engagingLaywersEngagingDashboardYourRatingTaskIdRoute
}

const engagingLaywersEngagingDashboardRouteChildren: engagingLaywersEngagingDashboardRouteChildren =
  {
    engagingLaywersEngagingDashboardMessagesRoute:
      engagingLaywersEngagingDashboardMessagesRouteWithChildren,
    engagingLaywersEngagingDashboardNotificationsRoute:
      engagingLaywersEngagingDashboardNotificationsRoute,
    engagingLaywersEngagingDashboardPaymentsRoute:
      engagingLaywersEngagingDashboardPaymentsRoute,
    engagingLaywersEngagingDashboardPostJobRoute:
      engagingLaywersEngagingDashboardPostJobRoute,
    engagingLaywersEngagingDashboardRatingsRoute:
      engagingLaywersEngagingDashboardRatingsRoute,
    engagingLaywersEngagingDashboardSettingsRoute:
      engagingLaywersEngagingDashboardSettingsRoute,
    engagingLaywersEngagingDashboardIndexRoute:
      engagingLaywersEngagingDashboardIndexRoute,
    engagingLaywersEngagingDashboardFundTaskTaskIdRoute:
      engagingLaywersEngagingDashboardFundTaskTaskIdRoute,
    engagingLaywersEngagingDashboardReviewProposalsTaskIdRoute:
      engagingLaywersEngagingDashboardReviewProposalsTaskIdRoute,
    engagingLaywersEngagingDashboardReviewWorkTaskIdRoute:
      engagingLaywersEngagingDashboardReviewWorkTaskIdRoute,
    engagingLaywersEngagingDashboardSubmitRatingTaskIdRoute:
      engagingLaywersEngagingDashboardSubmitRatingTaskIdRoute,
    engagingLaywersEngagingDashboardYourRatingTaskIdRoute:
      engagingLaywersEngagingDashboardYourRatingTaskIdRoute,
  }

const engagingLaywersEngagingDashboardRouteWithChildren =
  engagingLaywersEngagingDashboardRoute._addFileChildren(
    engagingLaywersEngagingDashboardRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  adminAdminDashboardRoute: adminAdminDashboardRouteWithChildren,
  assistingLawyersAssistingDashboardRoute:
    assistingLawyersAssistingDashboardRouteWithChildren,
  engagingLaywersEngagingDashboardRoute:
    engagingLaywersEngagingDashboardRouteWithChildren,
  landingpageIndexRoute: landingpageIndexRoute,
  engagingLaywersAuthLoginIndexRoute: engagingLaywersAuthLoginIndexRoute,
  engagingLaywersAuthRegisterIndexRoute: engagingLaywersAuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
